-- Makes every piece of copy on the Careers "Application" form
-- dashboard-editable (labels, hints, trust cards, button text, messages).
-- Phone/email are NOT stored here — the form pulls those live from Contact
-- page settings, so there is one source of truth.
-- Run in the Supabase SQL editor. Safe to re-run.

alter table careers_page_settings
  add column if not exists form_name_label text not null default 'Full name',
  add column if not exists form_name_label_ar text not null default 'الاسم الكامل',
  add column if not exists form_email_label text not null default 'Email',
  add column if not exists form_email_label_ar text not null default 'البريد الإلكتروني',
  add column if not exists form_phone_label text not null default 'Phone',
  add column if not exists form_phone_label_ar text not null default 'الهاتف',
  add column if not exists form_position_label text not null default 'Position',
  add column if not exists form_position_label_ar text not null default 'الوظيفة',
  add column if not exists form_experience_label text not null default 'Your experience',
  add column if not exists form_experience_label_ar text not null default 'خبراتك',
  add column if not exists form_experience_placeholder text not null default 'Tell us where you have worked and on what.',
  add column if not exists form_experience_placeholder_ar text not null default 'أخبرنا أين عملت وعلى ماذا.',
  add column if not exists form_cv_label text not null default 'Attach your CV (PDF)',
  add column if not exists form_cv_label_ar text not null default 'أرفق سيرتك الذاتية (PDF)',
  add column if not exists form_cv_hint text not null default 'PDF only, up to 3 MB. Optional, but it speeds up the review.',
  add column if not exists form_cv_hint_ar text not null default 'PDF فقط، حتى 3 ميجابايت. اختياري، لكنه يسرّع المراجعة.',
  add column if not exists form_trust1_title text not null default 'Confidential',
  add column if not exists form_trust1_title_ar text not null default 'سرّية تامة',
  add column if not exists form_trust1_body text not null default 'Your project information is kept private.',
  add column if not exists form_trust1_body_ar text not null default 'تبقى معلومات مشروعك خاصة.',
  add column if not exists form_trust2_title text not null default 'Response time',
  add column if not exists form_trust2_title_ar text not null default 'وقت الاستجابة',
  add column if not exists form_trust2_body text not null default 'We typically respond within one business day.',
  add column if not exists form_trust2_body_ar text not null default 'عادةً ما نستجيب خلال يوم عمل واحد.',
  add column if not exists form_trust3_title text not null default 'Experienced engineers',
  add column if not exists form_trust3_title_ar text not null default 'مهندسون ذوو خبرة',
  add column if not exists form_trust3_body text not null default '25+ years delivering complex projects.',
  add column if not exists form_trust3_body_ar text not null default 'أكثر من 25 عامًا في تنفيذ مشاريع معقدة.',
  add column if not exists form_send_label text not null default 'Send application',
  add column if not exists form_send_label_ar text not null default 'إرسال الطلب',
  add column if not exists form_sending_label text not null default 'Sending…',
  add column if not exists form_sending_label_ar text not null default 'جارٍ الإرسال…',
  add column if not exists form_call_label text not null default 'Call',
  add column if not exists form_call_label_ar text not null default 'اتصل بـ',
  add column if not exists form_footer_note text not null default 'Sent straight to {email}. We respond within 1 business day.',
  add column if not exists form_footer_note_ar text not null default 'يُرسَل مباشرة إلى {email}. نستجيب خلال يوم عمل واحد.',
  add column if not exists form_validation_error text not null default 'Please add your name, a valid email, and the position you''re applying for.',
  add column if not exists form_validation_error_ar text not null default 'يرجى إضافة اسمك وبريد إلكتروني صحيح والوظيفة المتقدم إليها.',
  add column if not exists form_send_error text not null default 'We couldn''t send that just now. Please try again, or email us at {email}.',
  add column if not exists form_send_error_ar text not null default 'تعذّر إرسال الطلب الآن. يرجى المحاولة مجددًا، أو مراسلتنا على {email}.',
  add column if not exists form_network_error text not null default 'We couldn''t reach our server. Please check your connection and try again.',
  add column if not exists form_network_error_ar text not null default 'تعذّر الوصول إلى الخادم. يرجى التحقق من اتصالك والمحاولة مجددًا.',
  add column if not exists form_success_heading text not null default 'Application received.',
  add column if not exists form_success_heading_ar text not null default 'تم استلام طلبك.',
  add column if not exists form_success_body text not null default 'Our team will review your application and get back to you within one business day.',
  add column if not exists form_success_body_ar text not null default 'سيراجع فريقنا طلبك ويعود إليك خلال يوم عمل واحد.';
